### ISSUE TITLE
0 Temperature

### ISSUE THREAD

**Issue by Censex** [bonezegei/Bonezegei_DHT11#1]
Hi,

Ive added you Library to my own Projekt and i got a problem. The Humidity works perfectly fine and changes in size. But the temperature ist not changing at all and only gives 0 back. I dont know if the sensor is broken or the code got a problem. I also got another Library for an LED Matrix maybe the Issue is comming from this. Im using an esp32 wroom 32.  Help is needed pls :)

**Comment by bonezegei** [comment]
Good Day, 

This library was tested using DHT11 and the same ESP32. I have no problem with the test. Kindly double check the connections. Or maybe the sensor is broker . Or maybe The sensor is DHT22. Thank you..

**Comment by Censex** [comment]
okay i checked the connections and the programm. The issue was that i was trying to print the float value but the matrix library can only handle int. Thanks for your help anyway.
